#!/usr/bin/env bash
# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi
# Check if the provided argument is an IP address
if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: Invalid IP address format"
    exit 1
fi
# Ping the IP address 5 times
ping -c 5 "$1"
